#!/bin/bash

[ -z "$1" ] && exit 0

if [ "$1" == "configure" ]; then
    ## add the gpg-key
    gpg --import /usr/share/linuxmuster-client-servertools/cloop-signing-key.gpg.pub

    ## handle configuration file changes from <=0.9d to later versions
    source /etc/linuxmuster/client-servertools.conf || true
    if [ -n "$CONF_GENERIC_POSTSYNC" ]; then
	echo "Disableing CONF_GENERIC_POSTSYNC, since it is now hardcoded and not configurable"
	sed -i "s/CONF_GENERIC_POSTSYNC/#disabled by packagemaintainer: CONF_GENERIC_POSTSYNC/" /etc/linuxmuster/client-servertools.conf || true
    fi
    if [ -n "$CONF_POSTSYNCDIR" ]; then
	echo "Disableing CONF_POSTSYNCDIR, since it is now hardcoded and not configurable"
	sed -i "s/CONF_POSTSYNCDIR/#disabled by packagemaintainer: CONF_POSTSYNCDIR/" /etc/linuxmuster/client-servertools.conf || true
    fi
fi


    

