#!/bin/bash
#############################################################################################
#  Installations-Skript für den Linuxclient
#  jesko.anschuetz@linuxmuster.net
#  frank@linuxmuster.net
#  10.07.2014
#  GPL v3
#############################################################################################

# Konfiguration lesen
. /etc/linuxmuster/client-servertools.conf || exit 1
# Funtionen einbinden
. /usr/share/linuxmuster-client-servertools/functions.inc || exit 1
# Netzwerkparameter linuxmuster.net
. /var/lib/linuxmuster/network.settings || exit 1

# deklaration der globalen arrays
declare -A TARGET_FILESET
declare -A SOURCE_FILESET

# Sanity checks beim skriptstart
check_startup

PATCHCLASS_SET=0
COMMONCLASS=""

# Optionen verarbeiten
while getopts ":a:c:p:l:H:" opt; do
case $opt in
    a)
        ACTION=$OPTARG
        ;;
    c)
        CLOOP_NAME=$OPTARG
        ;;
    p)	
	PATCHCLASS_SET=1
        PATCHCLASS=$OPTARG
        ;;
    l)
	LAPASS=$OPTARG
	;;
    H)
        HWCLASS=$OPTARG
        ;;
    \?)
        print_help
	exit 0
        ;;
esac
done


case $ACTION in
auto)
    if [ "x$HWCLASS" == "x" ]; then 
        exit_error "Die Option -H <hardwareklasse> muss angegeben werden."
    fi
    if [ "x$CLOOP_NAME" == "x" ]; then
        exit_error "Die Option -c <CloopName> muss angegeben werden."
    fi 

    list_available_images $CLOOP_NAME || exit_error "Konnte kein Cloop mit dem angegebenen Namen ($CLOOP_NAME) finden."

    PATCHCLASS_SET=1
    PATCHCLASS=$HWCLASS


    # Cloop herunterladen
    get_remote_cloop $HWCLASS $CLOOP_NAME
    # Cloop konfigurieren
    configure_cloop ${HWCLASS}.cloop

    ;;
get-cloop)
    if [ "x$HWCLASS" == "x" ]; then 
        exit_error "Die Option -H <hardwareklasse> muss angegeben werden."
    fi
    if [ "x$CLOOP_NAME" == "x" ]; then
        exit_error "Die Option -c <CloopName> muss angegeben werden."
    fi 
    list_available_images $CLOOP_NAME || exit_error "Konnte kein Cloop mit dem angegebenen Namen ($CLOOP_NAME) finden."
    get_remote_cloop $HWCLASS $CLOOP_NAME
    ;;
configure)
    configure_cloop $CLOOP_NAME
    ;;
set-postsync-pass)
    if [ $PATCHCLASS_SET -eq 0 ]; then 
	PATCHCLASS=""
    fi
    set_password_to_postsync $PATCHCLASS
    ;;
update-available)
    get_available_images
    ;;
list-available)
    list_available_images
    ;;
*)
    print_help
    ;;
esac

