#!/bin/bash

# Konfiguration lesen
. /etc/linuxmuster/client-servertools.conf || exit 1
# Funtionen einbinden
. /usr/share/linuxmuster-client-servertools/functions.inc || exit 1

cd $CONF_LINBODIR

STARTCONF=$(basename $1)
TARGETNAME=$2
TEMPDIR=$(mktemp -d -p .)

if [ "x$STARTCONF" == "x" ]; then 
    rm -rf $TEMPDIR
    exit_error "[ERROR] The start conf "
fi
if [ "x$TARGETNAME" == "x" ]; then 
    rm -rf $TEMPDIR
    exit_error "[ERROR] A target name for the package has to be given."
fi
if [ ! -f $STARTCONF ]; then
    rm -rf $TEMPDIR
    exit_error "[ERROR] Cannot open $STARTCONF"
fi

NUMOS=$(grep "\[OS\]" $STARTCONF | wc -l)
if [ $NUMOS -gt 1 ]; then 
    rm -rf $TEMPDIR
    cat <<MESSAGE
 Only a configuration with exactly one OS definition can be used to create
 a cloop package. Please change your start.conf accordingly.
MESSAGE
    exit_error "[ERROR] $NUMOS OS definitions found in $STARTCONF" 
fi

CLOOP=$(grep ^BaseImage $STARTCONF | awk -F"=" '{print $2}' | sed 's/#.*//' | xargs)
IMAGE=$(grep ^Image $STARTCONF  | awk -F"=" '{print $2}' | sed 's/#.*//' | xargs)
POSTSYNC=${CLOOP}.postsync

if [ "x$IMAGE" != "x" ]; then
    rm -rf $TEMPDIR
    exit_error "[ERROR] There is an rsync image in your config."
fi
if [ ! -f $POSTSYNC ]; then
    rm -rf $TEMPDIR
    exit_error "[ERROR] Cannot open $POSTSYNC"
fi

PATCHCLASS=$(grep ^PATCHCLASS $POSTSYNC | awk -F"=" '{print $2}' | sed -e 's/"//g' )

FilesToPack="${CLOOP} ${CLOOP}.info ${CLOOP}.desc"
DirToPack="/var/linbo/linuxmuster-client/$PATCHCLASS"

TarFile=${TARGETNAME}.tar
HWCLASS=$(echo $STARTCONF | sed -e "s/start\.conf\.//")

echo "Information:"
echo " Cloop name:     $CLOOP"
echo " Hardware class: $HWCLASS"
echo " Patchclass:     $PATCHCLASS"
echo 
echo "Creating package..."

STARTCONF_NEW=$(echo $STARTCONF | sed -e "s/$HWCLASS/$TARGETNAME/g")
CLOOP_NEW=${TARGETNAME}.cloop

echo " Adding $STARTCONF to package as $STARTCONF_NEW"
cp $STARTCONF $TEMPDIR/$STARTCONF_NEW
echo " Renaming cloop in $STARTCONF_NEW to $CLOOP_NEW"
sed -i "s/$CLOOP/$CLOOP_NEW/g" $TEMPDIR/$STARTCONF_NEW
echo " Adding $CLOOP to package as $CLOOP_NEW"
cp $CLOOP $TEMPDIR/$CLOOP_NEW
echo " Adding ${CLOOP}.info to package as ${CLOOP_NEW}.info"
cp ${CLOOP}.info $TEMPDIR/${CLOOP_NEW}.info
echo " Adding ${CLOOP}.desc to package as ${CLOOP_NEW}.desc"
cp ${CLOOP}.desc $TEMPDIR/${CLOOP_NEW}.desc

mkdir -p $TEMPDIR/linuxmuster-client/$TARGETNAME
echo " Adding patchfiles to package"
cp -r linuxmuster-client/$PATCHCLASS/* $TEMPDIR/linuxmuster-client/$TARGETNAME/

echo " Create tar-package"
cd $TEMPDIR
tar -cf ../$TARGETNAME.clpkg.tar . 
cd ..
echo " Calculate package hash"
md5sum $TARGETNAME.clpkg.tar > $TARGETNAME.clpkg.meta
rm -rf $TEMPDIR
echo "done."
echo 
echo "To publish this cloop to the comminuty, provide"
echo "the files:"
echo
echo "  $CONF_LINBODIR/$TARGETNAME.clpkg.tar"
echo "  $CONF_LINBODIR/$TARGETNAME.clpkg.meta"
echo
echo "to a maintainer who has write access to the"
echo "download server."


exit 0



