#!/bin/bash
#############################################################################################
#  Installations-Skript für den Linuxclient
#  jesko.anschuetz@linuxmuster.net
#  frank@linuxmuster.net
#  10.07.2014
#  GPL v3
#############################################################################################

# Konfiguration lesen
. /etc/linuxmuster/client-servertools.conf || exit 1
# Netzwerkparameter linuxmuster.net
. /var/lib/linuxmuster/network.settings || exit 1
# Hilfsfunktionen einbinden
. $CONF_HELPERFUNCTIONS || exit 1

# deklaration der globalen arrays
declare -A TARGET_FILESET
declare -A SOURCE_FILESET

# Sanity checks beim skriptstart
check_startup

# Default Hardwareklasse aus der Konfiguration
# kann durch Optio -h überschrieben werden
HWCLASS=$CONF_HWCLASS
CLOOP_NAME=$CONF_DEFAULT_CLOOP_NAME
PATCHCLASS=$CONF_DEFAULT_PATCHCLASS
PATCHCLASS_SET=0

# Optionen verarbeiten
while getopts ":a:h:c:p:l:" opt; do
case $opt in
    a)
        ACTION=$OPTARG
        ;;
    h)
        HWCLASS=$OPTARG
        ;;
    c)
        CLOOP_NAME=$OPTARG
        ;;
    p)	
	PATCHCLASS_SET=1
        PATCHCLASS=$OPTARG
        ;;
    l)
	LAPASS=$OPTARG
	;;
    \?)
        print_help
        ;;
esac
done


case $ACTION in
auto)
    colorecho "red" "Automodus: $ACTION $HWCLASS"
    colorecho "red" "NOT IMPLEMENTED YET"
    ;;
get-cloop)
    get_remote_cloop $HWCLASS $CLOOP_NAME
    ;;
configure)
    configure_cloop $CLOOP_NAME
    ;;
set-postsync-pass)
    if [ $PATCHCLASS_SET -eq 0 ]; then 
	PATCHCLASS=""
    fi
    set_password_to_postsync $PATCHCLASS
    ;;
update-available)
    get_available_images
    ;;
list-available)
    list_available_images
    ;;
*)
    print_help
    ;;
esac

