#!/bin/bash
#############################################################################################
#  Installations-Skript für den Linuxclient
#  jesko.anschuetz@linuxmuster.net
#  frank@linuxmuster.net
#  10.07.2014
#  GPL v3
#############################################################################################

# Konfiguration lesen
. /etc/linuxmuster/client-servertools.conf || exit 1
# Funtionen einbinden
. /usr/share/linuxmuster-client-servertools/functions.inc || exit 1
# Netzwerkparameter linuxmuster.net
#. /var/lib/linuxmuster/network.settings || exit 1

# deklaration der globalen arrays
declare -A TARGET_FILESET
declare -A SOURCE_FILESET

# Sanity checks beim skriptstart
check_startup

PATCHCLASS_SET=0
COMMONCLASS=""
FORCE=0

# Optionen verarbeiten
while getopts ":a:c:fp:H:" opt; do
case $opt in
    a)
        ACTION=$OPTARG
        ;;
    c)
        CLOOP_NAME=$OPTARG
        ;;
    f)
	FORCE=1
	;;
#    P)	
#	PATCHCLASS_SET=1
#        PATCHCLASS=$OPTARG
#        ;;
    p)
	LAPASS=$OPTARG
	;;
    H)
        HOSTGROUP=$OPTARG
        ;;
    \?)
        print_help
	exit 0
        ;;
esac
done


case $ACTION in
auto)
    if [ "x$CLOOP_NAME" == "x" ]; then
        exit_error "Die Option -c <Imagename> muss angegeben werden. $0 -h für weitere Hilfe."
    fi 
    # Hardwareklasse wird CLOOP_NAME verwendet, außer es wurde gesetzt
    HOSTGROUP=${HOSTGROUP:-$CLOOP_NAME}
    list_available_images $CLOOP_NAME || { list_available_images; exit_error "Konnte kein Cloop mit dem angegebenen Namen ($CLOOP_NAME) finden."; }

    #PATCHCLASS_SET=1
    #PATCHCLASS=$HOSTGROUP

    # Cloop herunterladen
    get_remote_cloop $HOSTGROUP $CLOOP_NAME
    # Cloop konfigurieren
    configure_cloop ${HOSTGROUP} $CLOOP_NAME

    ;;
get-cloop)
    if [ "x$CLOOP_NAME" == "x" ]; then
        exit_error "Die Option -c <Imagename> muss angegeben werden. $0 -h für weitere Hilfe."
    fi 
    # Hardwareklasse wird CLOOP_NAME verwendet, außer es wurde gesetzt
    HOSTGROUP=${HOSTGROUP:-$CLOOP_NAME}
    list_available_images $CLOOP_NAME || { list_available_images; exit_error "Konnte kein Cloop mit dem angegebenen Namen ($CLOOP_NAME) finden."; }
    get_remote_cloop $HOSTGROUP $CLOOP_NAME
    ;;
configure)
    if [ "x$CLOOP_NAME" == "x" ]; then
        exit_error "Die Option -c <Imagename> muss angegeben werden. $0 -h für weitere Hilfe."
    fi 
    # Hardwareklasse wird CLOOP_NAME verwendet, außer es wurde gesetzt
    HOSTGROUP=${HOSTGROUP:-$CLOOP_NAME}
    configure_cloop $HOSTGROUP $CLOOP_NAME
    ;;
set-postsync-pass)
    if [ "x$HOSTGROUP" == "x" ]; then
        exit_error "Die Option -H <hardware-class> muss angegeben werden. $0 -h für weitere Hilfe."
    fi 
    #if [ $PATCHCLASS_SET -eq 0 ]; then 
    #	PATCHCLASS=""
    #fi
    PATCHCLASS=$HOSTGROUP
    set_password_to_postsync $PATCHCLASS
    ;;
list-available)
    list_available_images
    ;;
*)
    print_help
    ;;
esac

