#!/bin/sh
if [ -e /mnt/passwords ]; then 
    echo " - patching password hashes"
    for line in $(cat /mnt/passwords); do
        user=$(echo $line | awk -F"|" '{print $1}')
        phash=$(echo $line | awk -F"|" '{print $2}')
        echo "      - $user"
        cp -a /mnt/etc/shadow /mnt/etc/shadow.new
        awk "BEGIN { OFS=FS =\":\" } ; \$1 == \"$user\" { \$2=\"$phash\" } { print }" /mnt/etc/shadow > /mnt/etc/shadow.new
        mv /mnt/etc/shadow.new /mnt/etc/shadow
    done    
    rm /mnt/passwords
    echo "  -done"
fi
