#!/bin/sh

STARTCONF=/start.conf
FSTAB=/mnt/etc/fstab

if [ -e $FSTAB ]; then
    echo -n " - fixing fstab: "
    echo -n "root: $ROOTDEV, "
    sed -i "s#\#dummyroot#$ROOTDEV#g" $FSTAB
    SWAP=$(sed ':a;N;$!ba;s/\n/;UMBRUCH;/g' $STARTCONF | sed 's/ //g'|sed 's/\[Partition\]/\n/g' | grep -i 'fstype=swap' | sed 's/;UMBRUCH;/\n/g' | grep -i 'dev=/' | cut -d'=' -f2 | head -c20 | cut -d"#" -f1)
    echo -n "swap: $SWAP, "
    sed -i "s#\#dummyswap#$SWAP#g" $FSTAB

    echo "done"
fi

