#!/bin/sh
if [ -e /mnt/etc/hosts ]; then
    echo " - fixing hosts"

    HOSTS=/mnt/etc/hosts
    sed -i "s/HOSTNAME/$HOSTNAME/g" ${HOSTS}

    echo "      - done"
fi

# done in linuxmuster-client
# Die network.settings vom Server muss auf dem Client zur Verfügung stehen
#. /mnt/etc/linuxmuster-client/server.network.settings
#sed -i "s/DOMAINNAME/$domainname/g" ${HOSTS}
#sed -i "s/\#SERVERIP/$serverip/g" ${HOSTS}

